### ISSUE TITLE
Changing the SKU on a product does not update the product stock entry, and it fatally errors when you try to resave with the same SKU because it already exists.

### ISSUE THREAD

**Issue by janetgatsby** [patpluspun/fmp_au#42]
@patpluspun  See recent issues with this for book title: Wheels on the Bus
![screen shot 2015-03-14 at 9 20 50 pm](https://cloud.githubusercontent.com/assets/7650441/6654299/64690078-ca90-11e4-8c8d-06b6ef40b22b.png)

From: Patrick Burch [mailto:patthropus@gmail.com]
Sent: Wednesday, 5 November 2014 3:39 PM
To: Emily Wan
Subject: Re: Website error

Ok, I know what the problem is, and how to fix it.  There is no good way of mitigating it currently though.
It appears that if you save a product SKU (which is what we're using for ISBN), it makes an entry for product stock.  Changing the SKU on a product does not update the product stock entry, and it fatally errors when you try to resave with the same SKU because it already exists.
I can fix this right now easily, but there is no way to prevent it in the future very easily, unless I patch the module we're using to handle product stock.
I will take a database backup and apply the fix to production, and then you should be able to add the product.  Is that ok?

---

**Comment by janetgatsby** [comment]
MORE ON THIS ISSUE FROM EMILY

 

When I was adding My Little Pony Equestria Girls Rainbow Rocks Novel to the website I accidently added in the ISBN for My Little Pony Equestria Girls Through The Mirror Novel.

 

To correct this I changed the title and cover image of Rainbow Rocks to that of Through The Mirror.

 

I then added in Rainbow Rocks – however when it saved a message came up saying to the effect that it has saved as a duplicate of Through The Mirror, and now, even though Rainbow Rocks is showing up as a separate book, each time you click on its link it redirects to Through The Mirror. Even when you click on it through the ‘Other Books In This Series’ link.

 

Could you please investigate this and fix as an urgent priority?

 

http://www.fivemile.com.au/catalog/new-releases-0 - if you click on Rainbow Rocks it redirects you to Through The Mirror

**Comment by janetgatsby** [comment]
@patpluspun Could you please look at this issue tonight?

**Comment by janetgatsby** [comment]
@patpluspun This is a priority issue, do you have time to work on this?

**Comment by patpluspun** [comment]
After some preliminary testing, the product stock issue is working as expected.  It was addressed in a previous fix I believe.  Here is a result of my testing:

```
MariaDB [fmp_au_dev]> select * from uc_product_stock where nid = '4290';
+---------------+------+--------+-------+-----------+
| sku           | nid  | active | stock | threshold |
+---------------+------+--------+-------+-----------+
| 9781760066384 | 4290 |      1 |  1000 |         0 |
+---------------+------+--------+-------+-----------+
1 row in set (0.00 sec)

MariaDB [fmp_au_dev]> select * from uc_product_stock where nid = '4290';
+---------------+------+--------+-------+-----------+
| sku           | nid  | active | stock | threshold |
+---------------+------+--------+-------+-----------+
| 9781760066383 | 4290 |      1 |  1000 |         0 |
+---------------+------+--------+-------+-----------+
1 row in set (0.00 sec)
```

**Comment by patpluspun** [comment]
@janetgatsby I will add hours for this ticket onto #40

**Comment by janetgatsby** [comment]
@patpluspun she's still having problems with Wheels on the Bus referenced at the top of this issue. 

The new book is redirecting to the old book. What needs to be done to fix this? I sort of remember this happening before. Is there something I can do in the CMS?

**Comment by patpluspun** [comment]
@janetgatsby we can always delete the old book to remove it completely, as long as the new item contains everything it needs to.  There's no use in having two of the same product.  I can remove it tomorrow with your approval.

**Comment by janetgatsby** [comment]
@patpluspun - yes please remove the old book and let's see what happens.

**Comment by janetgatsby** [comment]
@patpluspun   I went ahead and deleted the old book. Everything is working now! I'm closing this ticket, please let me know your hours.

**Comment by janetgatsby** [comment]
OK not so fast. If you could fix the following - there is a redirect loop error message on two of the titles from this ticket

http://www.fivemile.com.au/catalog/new-releases/my-little-pony-equestria-girls-through-mirror-novel
and
http://www.fivemile.com.au/catalog/new-releases/my-little-pony-equestria-girls-rainbow-rocks-novel

I see in your notes above that you corrected the redirect between these two books. Could you clear the loop error message please?

"Oops, looks like this request tried to create an infinite loop. We do not allow such things here. We are a professional website!"

**Comment by patpluspun** [comment]
@janetgatsby this is fixed on production.
